---
- name: Load OS-specific vars.
  include_vars: "{% raw %}{{ lookup('first_found', params) }}{% endraw %}"
  vars:
    params:
      files:
        - "{% raw %}{{ ansible_distribution }}{% endraw %}.yml"
        - "{% raw %}{{ ansible_os_family }}{% endraw %}.yml"
        - main.yml
      paths:
        - vars
